# Generated by Django 5.0.6 on 2024-07-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.CharField(max_length=255)),
                ('memory_usage', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='BotData',
            new_name='Bot_Data',
        ),
    ]
