# Generated by Django 5.0.6 on 2024-07-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_botlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_resources',
            name='latency',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
