# Generated by Django 5.0.6 on 2024-07-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bot_resources_latency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_resources',
            name='command_count',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot_resources',
            name='uptime',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
